spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://192.168.42.159/ecommerce
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
