spring:
  profiles:
    active: dev



---     
spring:
    profiles: test
    datasource: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ecommerces
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp


---     
spring:
    profiles: dev
    datasource: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://172.16.0.17:5432/ecommerce_yuki_sawamura
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp

#    server:
#        contextPath: /ecommerce-springC-sawamura 
server:
  context-path: /ecommerce-springC-sawamura
