spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ecommerce
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
security:
  basic:
    enabled: false
server:
  port: 8080
  tomcat:
    access-log-enabled: true
    access-log-pattern: "%h %l %u %t %r %s %d %D"
    basedir: /tmp