spring:
  profiles:
    active: test   



---     
spring:
    profiles: tests
    datasource: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ec_db
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
server:
  context-path: /ec-site

---     
spring:
    profiles: dev
    datasource: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://172.16.0.17:5432/ecommerce_yuki_sawamura
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp


server:
  context-path: /ec-site
