spring:
  profiles:
<<<<<<< HEAD
    active: dev



---     
spring:
    profiles: test
    datasource: 
=======
    active: test

---
spring:
    profiles: dev
    datasource:
>>>>>>> master
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://172.16.0.17:5432/ecommerce_yuki_sawamura
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
---     
spring:
    profiles: test
    datasource: 
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/student
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp

#    server:
#        contextPath: /ecommerce-springC-sawamura
<<<<<<< HEAD

---
spring:
    profiles: dev
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://172.16.0.17:5432/ecommerce_yuki_sawamura
        username: postgres
        password: postgres
    view:
        prefix: /WEB-INF/views/
        suffix: .jsp
        
server:
  context-path: /ecommerce-springC-sawamura
=======
server:
  context-path: /ecommerce-springC-sawamura
>>>>>>> master
